THIRDWEB_SECRET_KEY=8Bx3dlOcRmLYn_jZPV6pkGo54IxpGRecQhbXWxt1N2B7u5VMxqlLOxUlsJ0XFFNjkH-EMKQ6rAmyKUJQutL8pw
PINATA_API_KEY=4d5a08ccf667e8a0a34d
PINATA_SECRET_API_KEY=72c992a36a060c7a9d692dda274c0e81092980c4a79d18a7f526db8a1cc3499d
CONTRACT_ADDRESS=0xBA1F79Fb14449819477AD7018F1BD7E55cF11660  # Update after deploy
# For testnet: Use BaseSepolia in code
